cluster_size: 30
radius: 2
max_radius: 2.5
max_steps: 1000
stop_time: 100
step_size_interval: 20
filter_type: s
significant_figures: 2
database: ./results/basin_hopping.db
trajectory: ./results/basin_hopping_X30.traj