cluster_config:
  cluster_radius: 2
  cluster_size: 30
  pop_size: 24
employed_bee_config:
  enable: 1
  monte_carlo_search_f: 0.035
  search_method: 1
  search_size: 4
onlooker_bee_config:
  enable: 1
run_config:
  auto_stop: -1
  auto_stop_sf: 2
  is_parallel: 0
  maximum_cycle: 41
  minimum_cycle: 1
  run_id: 125
  time_out: -1
  view_traj: 0
scout_bee_config:
  check_energies_every_x_loops: 1
  count: 3
  enable: 1
  energy_abnormal: 0.6
  energy_difference: 1
  update_energies: 1
