children_perc: 0.8
cluster_radius: 2.0
cluster_size: 10
db_file: genetic_algorithm_results.db
delta_energy_thr: 0.1
fitness_func: exponential
mating_method: roulette
max_gen: 50
max_no_success: 50
pop_size: 20
results_dir: ./results
reuse_state: false
run_id: 10
show_plot: true
time_lim: 100
