general:
  cluster_radius: 2.0
  cluster_size: 10
  delta_energy_thr: 0.1
  gens_until_exchange: 10
  pop_size: 20
mating:
  children_perc: 0.8
  fitness_func: exponential
  mating_method: roulette
results:
  db_file: genetic_algorithm_results.db
  results_dir: results
run_id: 4
stop_conditions:
  max_exchanges_no_success: 3
  max_gen: 50
  time_lim: 600
