children_perc: 0.8
cluster_radius: 2.0
cluster_size: 4
db_file: genetic_algorithm_results.db
delta_energy_thr: 0.1
fitness_func: exponential
mating_method: roulette
max_gen: 50
max_no_success: 50
pop_size: 5
reuse_state: false
run_id: 3
show_plot: false
time_lim: 100
