children_perc: 0.8
# Change the cluster radius to be cluster_size^{1/3} at one point
cluster_radius: 2.0
cluster_size: 3
delta_energy_thr: 0.1
fitness_func: exponential
mating_method: roulette
max_gen: 50
max_no_success: 5
pop_size: 20
run_id: 97
